MODEL:
  DEVICE: "cuda"
  DEVICE_IDS: "'0'"
  NAME: 'efficient_unet'
  N_CHANNEL: 3
  N_CLASS: 8
  LABEL_SMOOTH: False
  DROPOUT: 0.5
  WEIGHT: '/cache/efficientnet-b2-27687264.pth'
  UNET:
    ENCODE_DIM: 32
    BILINEAR: True
    SCSE: True
    DBLOCK: False
    ATTENTION_BLOCK: False
    RRCNN_BLOCK: False
    RRCNN_BLOCK_T: 2
  EFFICIENT_UNET:
    BACKBONE_NAME: 'efficientnet-b2'
    CONCAT_INPUT: True
    ATTENTION_BLOCK: False


INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

  PIXEL_MEAN: [0.5716390795822704,0.5191239166003989,0.4923358870147872]
  PIXEL_STD: [0.24454287910934064,0.2379462921336855,0.22901043133634436]
  NORMALIZATION: True
  USE_MIX_UP: False
  USE_AUGMIX: False

DATASETS:
  NAMES: ('Base')
  CLASS_NAMES: ['水体', '交通运输', '建筑', '耕地', '草地', '林地', '裸土', '其它']
  DATA_PATH: '/cache/naic_rs/'
  IMG_SUFFIX: '.tif'
  SEG_MAP_SUFFIX: '.png'
  IMAGE_FOLDER: 'imgs'
  GT_FOLDER: 'gts'

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: "Adam"
  SYNCBN: False

  BASE_LR: 3e-4
  MIN_LR: 3e-6
  BIAS_LR_FACTOR: 1
  USE_WARMUP: True

  MOMENTUM: 0.9

  WEIGHT_DECAY: 5e-4
  WEIGHT_DECAY_BIAS: 5e-4

  GAMMA: 0.1
  STEPS: [30, 50]

  WARMUP_FACTOR: 0.01
  WARMUP_EPOCH: 10
  WARMUP_BEGAIN_LR: 3e-06
  WARMUP_METHOD: "linear"

  
  MAX_EPOCHS: 60
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 20
  EVAL_PERIOD: 4
  TRAIN_LOG: False
  START_SAVE_EPOCH: 50
  START_EVAL_EPOCH: 50
#  START_SAVE_EPOCH: 0

  PER_BATCH: 64
  FP16: True
  TENSORBOARD:
    USE: True
    LOG_PERIOD: 20
TEST:
  WEIGHT: r'/cache/epoch_60.pth'
  # IMAGE_FOLDER: r'/cache/naic_rs/imgs/val'
  IMAGE_FOLDER: r'/cache/image_B'
  FLIP_AUG: False

OUTPUT_DIR: "/cache/unet_baseline_60"

#TEST:
#  WEIGHT: r'/usr/demo/hexin/new_dataset/unet_test/unet_epoch2.pth'
#
#OUTPUT_DIR: "/usr/demo/hexin/new_dataset/unet_test"


