MODEL:
  DEVICE: "cuda"
  DEVICE_IDS: "'0'"
  NAME: 'res_unet_3plus'
  N_CHANNEL: 3
  N_CLASS: 17
  LABEL_SMOOTH: False
  DROPOUT: 0.0
  # WEIGHT: '/cache/resnet50-19c8e357.pth'
  WEIGHT: '/cache/resnet34-333f7ec4.tar'
  # WEIGHT: '/cache/resnest50-528c19ca.pth'
  # UNET:
  #   ENCODE_DIM: 32
  #   BILINEAR: True
  #   SCSE: False
  #   DBLOCK: False
  #   ATTENTION_BLOCK: False
  #   RRCNN_BLOCK: False
  #   RRCNN_BLOCK_T: 2
  # EFFICIENT_UNET:
  #   BACKBONE_NAME: 'efficientnet-b2'
  #   CONCAT_INPUT: True
  #   ATTENTION_BLOCK: False
  # DEEPLAB_V3_PLUS:
  #   BACKBONE_NAME: 'xception'
  #   AUX:  True
  #   DILATED: True
  # DLINKNET:
  #   BACKBONE_NAME: 'resnet34'
  #   SCSE: True
  #   MISH: True
  #   SPP: True
  #   GEM: False
  #   INPLACE_ABN: False
  #   ACF: False

  # RES_UNNET:
  #   BACKBONE_NAME: 'resnet34'
  #   SCSE: True
  #   MISH: False
  #   DB_BLOCK: False
  #   SPP: False
  #   HYPERCOLUMN: False
  #   ATT_BLOCK: False
  #   SPHEAD: True
  RES_UNET_3PLUS:
    BACKBONE_NAME: 'resnet34'
    SCSE: True


INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

  PIXEL_MEAN: [0.35540336386467425,0.383968561837589,0.3592760263863359]
  PIXEL_STD: [0.1368416254486153,0.1363384775173113,0.13798154077383737]
  NORMALIZATION: True
  USE_MIX_UP: False
  USE_AUGMIX: False



DATASETS:
  NAMES: ('Base')
  CLASS_NAMES: ['水体', '道路', '建筑物', '机场', '火车站', '光伏', '停车场', '操场', '普通耕地', '农业大棚', '自然草地', '绿地绿化', '自然林', '人工林', '自然裸土', '人为裸土', '其它']
  DATA_PATH: '/cache/naic_rs/'
  IMG_SUFFIX: '.tif'
  SEG_MAP_SUFFIX: '.png'
  IMAGE_FOLDER: 'imgs'
  GT_FOLDER: 'gts'

DATALOADER:
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: "SGD"
  SYNCBN: False

  BASE_LR: 5e-3
  MIN_LR: 1e-6
  BIAS_LR_FACTOR: 1
  USE_WARMUP: True

  MOMENTUM: 0.9

  WEIGHT_DECAY: 5e-4
  WEIGHT_DECAY_BIAS: 5e-4

  LR_SCHEDULER: 'cosine_annealing'
  GAMMA: 0.1
  STEPS: [20, 30, 50]

  WARMUP_FACTOR: 0.01
  WARMUP_EPOCH: 10
  WARMUP_BEGAIN_LR: 3e-06
  WARMUP_METHOD: "linear"

  SWA: False
  SWA_LR: 2e-3
  SWA_START: 75

  
  MAX_EPOCHS: 120
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 20
  EVAL_PERIOD: 4
  TRAIN_LOG: False
  START_SAVE_EPOCH: 60
  START_EVAL_EPOCH: 0
#  START_SAVE_EPOCH: 0

  PER_BATCH: 48
  FP16: True
  RESUME: False
  RESUME_CHECKPOINT: r'/cache/epoch_60.pth'
  TENSORBOARD:
    USE: True
    LOG_PERIOD: 20
TEST:
  WEIGHT: r'/usr/demo/hexin/new_dataset/unet_baseline_150/unet_epoch147.pth'
  FLIP_AUG: False

OUTPUT_DIR: "/cache/unet_baseline_60"

#TEST:
#  WEIGHT: r'/usr/demo/hexin/new_dataset/unet_test/unet_epoch2.pth'
#
#OUTPUT_DIR: "/usr/demo/hexin/new_dataset/unet_test"


