MODEL:
  DEVICE: "cuda"
  DEVICE_IDS: "'0,1'"
  NAME: 'hrnet'
  N_CHANNEL: 4
  N_CLASS: 10
  LABEL_SMOOTH: False
  DROPOUT: 0.0

  WEIGHT: r'E:/src/seg/pretrain/hrnetv2_w18_imagenet_pretrained.pth'

  LOSS_TYPE: 'large_margin'

  CLASS_WEIGHT: [1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 5.0]

  HRNET:
    BACKBONE_NAME: 'hrnetv2_18'



INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]


  PIXEL_MEAN: [0.485, 0.456, 0.406, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225, 0.225]
  NORMALIZATION: True
  USE_MIX_UP: True
  USE_CUT_MIX: False
  USE_COPY_PASTE: False

  USE_RESIZE: False
  USE_VFLIP: False
  USE_HFLIP: True
  USE_RANDOMROTATE90: True
  USE_SHIFTSCALEROTATE: True
  USE_HUESATURATIONVALUE: False
  USE_RGBSHIFT: True
  USE_RANDOMBRIGHTNESSCONTRAST: False
  USE_CLAHE: False
  USE_RANDOMGAMMA: False
  USE_GRIDMASK: False
  USE_BLUR: False
  USE_GAUSSNOISE: False
  USE_ELASTICTRANSFORM: False
  USE_CUTOUT: False

DATASETS:
  NAMES: ('Base')
  CLASS_NAMES: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
  DATA_PATH: r'E:/suichang_round2_train_210316/split_dataset1/'
#  DATA_PATH: '/home/xieyi/SSD/xieyi/Detetection/seg/tc_data/split_dataset'
  IMG_SUFFIX: '.tif'
  SEG_MAP_SUFFIX: '.png'
  REDUCE_ZERO_LABEL: True
  TRAIN_IMAGE_FOLDER: 'train/imgs'
  TRAIN_GT_FOLDER: 'train/gts'
  VAL_IMAGE_FOLDER: 'val/imgs'
  VAL_GT_FOLDER: 'val/gts'

DATALOADER:
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  WEIGHT_DECAY_BIAS: 5e-4


  SYNCBN: False

  MULTI_SCALE: []

  BASE_LR: 1e-2
  MIN_LR: 1e-4
  BIAS_LR_FACTOR: 1


  LR_SCHEDULER: 'cosine_annealing'
  GAMMA: 0.1
  STEPS: [5, 10]
  T_MAX: 5
  MILESTONES: [1]

  USE_WARMUP: False
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCH: 10
  WARMUP_BEGAIN_LR: 5e-05
  WARMUP_METHOD: "linear"

  SWA: False


  MAX_EPOCHS: 160
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 100
  EVAL_PERIOD: 20
  TRAIN_LOG: False
  START_SAVE_EPOCH: 0
  START_EVAL_EPOCH: 0

  PER_BATCH: 16
  FP16: True
  RESUME: False
  RESUME_CHECKPOINT: r'/cache/epoch_60.pth'
  TENSORBOARD:
    USE: True
    LOG_PERIOD: 20
TEST:
  WEIGHT: r'/usr/demo/hexin/new_dataset/unet_baseline_150/unet_epoch147.pth'
  FLIP_AUG: False

OUTPUT_DIR: r"E:\src\seg\model"

#TEST:
#  WEIGHT: r'/usr/demo/hexin/new_dataset/unet_test/unet_epoch2.pth'
#
#OUTPUT_DIR: "/usr/demo/hexin/new_dataset/unet_test"


